name: Release
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      RUNNER: github
      NODE_ENV: dev
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
      - name: Install global Node.js dependencies
        run:  npm i node-sass -g
      - name: Install local Node.js dependencies
        run:  npm i
      - name: Build local project
        run:  npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            dist
          retention-days: 3
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      RUNNER: github
      NODE_ENV: dev
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
      - name: Install global OS dependencies
        run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install local Node.js dependencies
        run:  npm i
      - name: Create dist directory
        run: mkdir dist
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist
      - name: Run E2E tests
        run: npm run start & npm run cypress:run
        env:
          CI: true
  release-github:
    name: Release on Github
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashfiles('**/package-lock.json') }}
      - name: Github checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
      - name: Create Github release
        uses: konfer-be/action-create-release-from-tag@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  release-npm:
    name: Release on NPM registry
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashfiles('**/package-lock.json') }}
      - name: Github checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Create dist directory
        run: mkdir -p dist
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist
      - name: Release on NPM
        run: npm ci & npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.KONFER_NPM_TOKEN }}